version: '3.3'
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  backend:   
    tty: true
    image: docker.io/susanmwangi/yolo-backend:0.0.0
    ports:
      - "5000:5000"

    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yolomy
    networks:
      - yolo-network
  client:
    tty: true
    image: docker.io/susanmwangi/yolo-client:0.0.1
    ports:
      - "3000:3000"
    networks:
      - yolo-network
    depends_on:
      - backend
networks:
 yolo-network:
    name: yolo-network
    driver: bridge