version: '3.3'

services:
  db:
    image: docker-node-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  backend:   
    image: docker.io/susanmwangi/yolo-backend:0.0.0
    ports:
      - "5000:5000"

    environment:
      MONGO_URL: mongodb://127.0.0.1:27017/mydb
    networks:
      - yolo-project-network
  client:
    image: docker.io/susanmwangi/yolo-client:0.0.1
    ports:
      - "3000:3000"
    networks:
      - yolo-project-network
    depends_on:
      - backend
networks:
  yolo-project-network:
    driver: bridge