apiVersion: apps/v1
kind: Deployment
metadata:
  name: backed-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      spec:
      containers:
        - name: backend
          image: susanmwangi/yolo-backend:0.0.0
          ports:
            - containerPort: 5000

          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/yolomy
          command: ["npm", "run", "start"]
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          hostPath:
            path: /data/mongodb
            
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: yolobackend-service
spec:
  selector:
    app.kubernetes.io/name: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000