apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      spec:
      containers:
        - name: client
          image: susanmwangi/yolo-client:0.0.1
          ports:
            - containerPort: 3000
              targetPort: 3000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/yolomy
          command: ["npm", "start"]

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: yoloclient-service
spec:
  selector:
    app.kubernetes.io/name: client
  ports:
    - protocol: TCP
      port: 3000
      
    