---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: yoloclient
    component: client
  annotations:
    description: "Service for client application"
spec:
  type: LoadBalancer
  selector:
    app: yoloclient
    component: client
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000